spring.application.name=gulimall-coupon
#spring.cloud.nacos.config.namespace=e8e9b731-6a88-40c0-a046-a470081ff46f
#spring.cloud.nacos.config.ext-config[0]=nacos:{other.properties}?group={dev}
#spring.cloud.nacos.config.ext-config[1]=nacos:{database.properties}?group={dev}
#spring.cloud.nacos.config.ext-config[2]=nacos:{mybatis.properties}?group={dev}
#spring.cloud.nacos.config.ext-config[3]=nacos:{server.properties}?group={dev}