spring.application.name=gulimall-gateway
spring.cloud.nacos.config.server-addr=10.173.1.224:8848
spring.cloud.nacos.config.namespace=33d421db-4269-478d-90ce-33cd22309aa7
spring.config.import=optional:nacos:gulimall-gateway.yaml?group=dev
spring.cloud.nacos.password=nacos
spring.cloud.nacos.username=nacos
spring.cloud.nacos.discovery.server-addr=10.173.1.224:8848

server.port=88