spring.application.name=gulimall-third-party
#spring.cloud.nacos.config.server-addr=192.168.123.84:8848
spring.cloud.nacos.config.server-addr=10.201.215.224:8848
spring.cloud.nacos.config.namespace=14363e22-b42e-4b10-8a85-4bfbbb108d5f
spring.config.import=optional:nacos:oss.properties?group=dev
spring.cloud.nacos.password=nacos
spring.cloud.nacos.username=nacos
#spring.cloud.nacos.discovery.server-addr=192.168.123.84:8848
spring.cloud.nacos.discovery.server-addr=10.201.215.224:8848

server.port=20000

