spring:
  application:
    name: gulimall-ware

  cloud:
    nacos:
      # 全局地址和账号，discovery 和 config 都继承
      server-addr: 10.173.1.224:8848
      username: nacos
      password: nacos

      discovery:

      config:
        namespace: 384e6817-b4d0-4e33-8279-a0597727fe4f
        file-extension: yaml

  # 用 import 替代老版本的 ext-config
  config:
    import:
      - optional:nacos:gulimall-ware.yml?group=dev&refreshEnabled=true
